interface RandomWord {
  word: string;
  image?: string;
}

export const RandomWords: Array<RandomWord> = [
  /* Animais */
  { word: 'Avestruz' },
  { word: 'Baleia' },
  { word: 'Borboleta' },
  { word: 'Cachorro' },
  { word: 'Camarão' },
  { word: 'Cavalo' },
  { word: 'Cobra' },
  { word: 'Escorpião' },
  { word: 'Estrela-do-mar' },
  { word: 'Galinha' },
  { word: 'Gato' },
  { word: 'Lagosta' },
  { word: 'Leão' },
  { word: 'Lula' },
  { word: 'Papagaio' },
  { word: 'Peixe' },
  { word: 'Porco' },
  { word: 'Rato' },
  { word: 'Rinoceronte' },
  { word: 'Tartaruga' },
  { word: 'Tubarão' },
  { word: 'Urso' },
  { word: 'Vaca' },
  /* Natureza */
  { word: 'Árvore' },
  { word: 'Flor' },
  { word: 'Planta' },
  /* Alimentos */
  { word: 'Bacon' },
  { word: 'Banana' },
  { word: 'Cogumelo' },
  { word: 'Macarrão' },
  { word: 'Maçã' },
  { word: 'Mel' },
  { word: 'Morango' },
  { word: 'Pato' },
  { word: 'Pimenta' },
  { word: 'Presunto' },
  { word: 'Queijo' },
  { word: 'Sal' },
  { word: 'Salada' },
  { word: 'Uva' },
  { word: 'Vinho' },
  /* Profissões */
  { word: 'Ator' },
  { word: 'Bombeiro' },
  { word: 'Caçador' },
  { word: 'Detetive' },
  { word: 'Escritor' },
  { word: 'Enfermeio' },
  { word: 'Engenheiro' },
  { word: 'Espião' },
  { word: 'Garçom' },
  { word: 'Médico' },
  { word: 'Mergulhador' },
  { word: 'Motorista' },
  { word: 'Ninja' },
  { word: 'Padeiro' },
  { word: 'Pescador' },
  { word: 'Pirata' },
  { word: 'Professor(a)' },
  { word: 'Samurai' },
  { word: 'Veterinário' },
  /* Objetos */
  { word: 'Armário' },
  { word: 'Balão' },
  { word: 'Bermuda' },
  { word: 'Cachecol' },
  { word: 'Cadeira' },
  { word: 'Cama' },
  { word: 'Capacete' },
  { word: 'Chapéu' },
  { word: 'Cartas' },
  { word: 'Dado' },
  { word: 'Esponja' },
  { word: 'Flauta' },
  { word: 'Garrafa' },
  { word: 'Guarda-Chuva' },
  { word: 'Guardanapo' },
  { word: 'Harpa' },
  { word: 'Impressora' },
  { word: 'Janela' },
  { word: 'Lâmpada' },
  { word: 'Máscara' },
  { word: 'Ouro' },
  { word: 'Pá' },
  { word: 'Pena' },
  { word: 'Porto' },
  { word: 'Rádio' },
  { word: 'Refrigerante' },
  { word: 'Remédio' },
  { word: 'Taça' },
  { word: 'Televisão' },
  { word: 'Tesoura' },
  { word: 'Termômetro' },
  /* Meios de Transporte */
  { word: 'Avião' },
  { word: 'Carro' },
  { word: 'Helicóptero' },
  { word: 'Motocicleta' },
  { word: 'Navio' },
  { word: 'Ônibus' },
  { word: 'Trator' },
  { word: 'Trem' },
  /* Partes do Corpo */
  { word: 'Cabeça' },
  { word: 'Dente' },
  { word: 'Mão' },
  { word: 'Nariz' },
  { word: 'Perna' },
  { word: 'Pé' },
  /* Lugares */
  { word: 'Aeroporto' },
  { word: 'Cemitério' },
  { word: 'Farmácia' },
  { word: 'Igreja' },
  { word: 'Ilha' },
  { word: 'Parque' },
  { word: 'Praia' },
  /* Jogos */
  { word: 'Boliche' },
  { word: 'Golfe' },
  { word: 'Futebol' },
  { word: 'Vôleibol' },
  /* Clima */
  { word: 'Chuva' },
  { word: 'Lava' },
  { word: 'Lua' },
  { word: 'Neve' },
  { word: 'Nuvem' },
  { word: 'Sol' },
  { word: 'Tempestade' },
  /* Outros */
  { word: 'Extraterrestre' },
  { word: 'Dragão' },
  { word: 'Espaço (Sideral)' },
  { word: 'Fantasma' },
  { word: 'Filme' },
  { word: 'Labirinto' },
  { word: 'Lobisomen' },
  { word: 'Meteoro' },
  { word: 'Múmia' },
  { word: 'Túnel' },
  { word: 'Unicórnio' },
  { word: 'Vampiro' },
  { word: 'Zumbi' },
];
